---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-postgres
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/db-postgres
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
