---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-postgres
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/db-postgres
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgres
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: db-postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: database
type: Opaque
data:
  POSTGRES_HOST_AUTH_METHOD: dHJ1c3Q=
  POSTGRES_PASSWORD: b3NVbUFldDI0NnFv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
spec:
  selector:
    matchLabels:
      db/app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db/app: postgresql
    spec:
      containers:
      - image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "10Gi"
            cpu: "3"
        envFrom:
        - secretRef:
            name: postgresql
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-postgres
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - sydney
      volumes:
      - name: db-postgres
        persistentVolumeClaim:
          claimName: db-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    notice: db-postgres
  name: db-postgres
spec:
  type: LoadBalancer
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  selector:
    db/app: postgresql
